### PR TITLE
as -> AS

### PR DESCRIPTION
**Pull request by bjornjorgensen**
image

### CODE REVIEW

**Comment by benz0li** [comment]
Could you submit Pull Requests to the GitLab repository? https://gitlab.com/b-data/jupyterlab/python/docker-stack.

If not, I will find another way.

**Comment by benz0li** [comment]
P.S.: I have not linted Shell- and Dockerfiles yet. Will do so when I have got more time.

**Comment by benz0li** [comment]
P.P.S.: Going to use [ShellCheck](https://github.com/koalaman/shellcheck) and [hadolint](https://github.com/hadolint/hadolint).

**Comment by bjornjorgensen** [comment]
well its not everyday that I use gitlab so when I logged in there now I get this

image

:( 

But there are one more thing I will like to change 
`FROM ${BUILD_ON_IMAGE}:${PYTHON_VERSION}${CUDA_IMAGE_FLAVOR:+-}${CUDA_IMAGE_FLAVOR} AS files`

so in the end, you end up with files files and even more files..  like this
```
## Copy files as late as possible to avoid cache busting
COPY --from=files /files /
COPY --from=files /files/var/backups/skel ${HOME}

```
Change that to base or base_image_with_files ? 

I like this project, but reading it and figure out what how this is build up, is quit hard.

**Comment by bjornjorgensen** [comment]
> 
> > I like this project, but reading it and figure out what how this is build up, is quit hard.
> 
> Yes. This is due to the fact that the regular and CUDA-enabled images can be built with the same Dockerfile.

I'm more thinking about  when there are folder like `common/subtags` witch have a `docker` folder with a `Dockerfile` and there are also a folder `root` with a `Dockerfile` and there are no documentation for what the do or why they are there.

**Comment by benz0li** [comment]
Resolved by https://github.com/b-data/jupyterlab-python-docker-stack/commit/24fe8a5aa8cb546234799c5a71e60fedbe0e3949

**Pull request closed without merging**
